# Generated by Django 2.0.1 on 2018-01-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180107_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hdyhau',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
