# Generated by Django 2.0.1 on 2018-01-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180108_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
        ),
    ]
