# Generated by Django 2.0.1 on 2018-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180114_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Producer', 'Producer'), ('Other', 'Other')], default='', max_length=1, null=True),
        ),
    ]
