# Generated by Django 2.0.1 on 2018-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180114_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('B', 'Buyer'), ('P', 'Producer'), ('O', 'Other')], default='', max_length=1, null=True),
        ),
    ]
