# Generated by Django 2.0 on 2018-03-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_blogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
