# Generated by Django 2.0 on 2018-03-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180330_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
