# Generated by Django 2.0 on 2018-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180330_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Producer', 'Producer'), ('Other', 'Other')], default='', max_length=8, null=True),
        ),
    ]
